### PR TITLE
fixGuide): Fix doc guide and other small thing

### LINKED ISSUE #2936: [BUG] Data table pinned column
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.
No

**Current Behavior**
A concise description of what you're experiencing.
When we hide a pinned data table column, ui is wrong
 
**Expected Behavior**
A concise description of what you expected to happen.
We should remove these colum from show / hide or prevent this weird effect

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/demo-function-event.html
2. Click on Data table and open one
3. Clcik on show/hide button and hide one of the 3 first column

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

* Fix guide format
* Fix bug with search
* Clean unused images
* add missing new functions
* Add info for chart

* fix the pin column data table hide/show that break the table
* fix the default tabs override the user tabs in appbar and footer
* fix test geometry z index value

* Reduce padding id tatable
* Fix the data table creation on selectedLAyerPath

* Update chart version

Fixes #2936

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted Dec 5, 5:45 https://jolevesq.github.io/geoview/index.html
* Check the guide to see new doc and style
* Run test map 4 see test is passing
* Go to Sandbox and set different tab to see they are applied properly
* Go to data table and see icon, zoom and details not part of hide column anymore

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/3194)

### CODE REVIEW

File: packages/geoview-core/src/core/components/guide/guide.tsx
Comment (jaredkinger) [inline packages/geoview-core/src/core/components/guide/guide.tsx]: This is generating `<article><article>content...</article></article>`. Remove the `options={{ wrapper: 'article' }}` on line 149 to get rid of the extra article tag.

File: packages/geoview-core/public/locales/en/translation.json
Comment (jaredkinger) [inline packages/geoview-core/public/locales/en/translation.json]: There is a leading space in '' filters" line 353

File: packages/geoview-core/src/core/components/guide/guide-style.ts [hunk 1]
```diff
@@ -18,31 +18,75 @@ export const getSxClasses = (theme: Theme): SxStyles =>
...
           },
         },
         '& h3': {
           marginBottom: '5px',
           marginTop: '20px',
+          paddingBottom: '5px',
+          fontSize: theme.palette.geoViewFontSize.md,
+          fontWeight: 600,
+          borderBottom: `1px solid ${theme.palette.geoViewColor.bgColor.dark[400]}`,
+          '& p': {
```
[the remark this answers is not in the document]
Comment (jolevesq) [reply packages/geoview-core/src/core/components/guide/guide-style.ts]: We should not... This seems to be there for a while, I will remove
